[project]
name = "miningphrases"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.0",
    "google-genai>=1.64.0",
    "pillow>=12.1.1",
    "pyperclip>=1.11.0",
    "requests>=2.32.5",
]
